Add the Snakedex page
Snakeroom/Website pull request #19
Opened 2022-11-03 06:22 UTC by haykam821

2022-11-03 06:26 UTC, Megadynamite approved these changes

2022-11-03 23:56 UTC, Megadynamite requested changes
I'd appreciate the endpoint being changed from by_snake_number to by_number and will subsequently submit a corresponding pr to the website.

2022-11-04 18:45 UTC, Melissa0x1f992 commented
how do I review on GitHub mobile

2022-11-04 18:46 UTC, Melissa0x1f992 approved these changes
I didn't look at the code. Site looks good 👍

2022-11-04 19:08 UTC, merged